# Generated by Django 6.0.3 on 2026-03-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='faculty',
            field=models.CharField(choices=[('FNAS', 'Faculty of Natural & Applied Science'), ('FHS', 'Faculty of Health Science'), ('FSS', 'Faculty of Social Science'), ('FMS', 'Faculty of Management Science'), ('FAS', 'Faculty of Art'), ('FAGR', 'Faculty of Agricultural Science')], default='FNAS', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='matric_number',
            field=models.CharField(default='PLASU/0000/FNAS/0000', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='biometric_pin',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
