# Generated by Django 6.0.3 on 2026-05-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_account_status_patient_status_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='biometric_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
