# Generated by Django 6.0.3 on 2026-05-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP Record'},
        ),
    ]
